#
# native build makefile for optim
#
# micronix/hitech/optim/makefile
#
# Changed: <2023-06-25 15:08:30 curt>

TARGETS = optim

CSRCS = optim1.c part21.c part31.c ctype1.c initvar1.c

optim:	$(CSRCS)
	cc -o optim $(CSRCS)
 
clean:

clobber: clean
	rm -f $(TARGETS)

# vim: tabstop=4 shiftwidth=4 noexpandtab:

